### ISSUE TITLE
Proxy .htaccess improvements

### ISSUE THREAD

**Issue by wjcrowcroft** [currencybot/open-exchange-rates#15]
The proxy server could use some .htaccess optimisations.. I'm specifically thinking of compression - stripping whitespace and maybe gzipping, unless a specific parameter is appended, such as `prettyprint` or `format`. The files are stored in a readable (uncompressed) format but it's obviously not the optimal way to send them.

If anybody has any ideas to share on Apache and .htaccess for tarting up the openexchangerates.org proxy, please reply here!

**Comment by storytracer** [comment]
I was thinking about that just the other day, since I love gzip compression. The speed advantage may not seem that big in our case, but when your using a smartphone and coverage sucks in your area, you are happy about every single byte not sent.
Basically enabling gzip compression is pretty simple:

If mod_deflate is not yet enabled on your server, enable it:

`$ a2enmod deflate`

Restart apache after the change.

Then add this line to your .htaccess file to enable compression for json and jsonp files:

`AddOutputFilterByType DEFLATE application/json application/javascript`

But in combination with caching there is still the question at which point exactly the server compresses the files. Does he compress them before or after caching, which is a huge difference in CPU load?

Do you think you could share your .htaccess file with me? I'd like to try different configurations and see which one is performing best, both in terms of request time and server load.

As for whitespace stripping I haven't found any server-side solution yet, it seems to be too CPU intensive. But I'll keep looking.
